import type { IconType } from "react-icons";
import {
  FaAward,
  FaBagShopping,
  FaBolt,
  FaBorderAll,
  FaBullseye,
  FaCalendarDays,
  FaCalendarWeek,
  FaCheckDouble,
  FaCoins,
  FaCompass,
  FaCrown,
  FaDrum,
  FaEarthAmericas,
  FaExplosion,
  FaFaceSmile,
  FaFire,
  FaGamepad,
  FaGear,
  FaGem,
  FaGuitar,
  FaHandshake,
  FaHourglassHalf,
  FaHouse,
  FaIdCard,
  FaImage,
  FaLink,
  FaLock,
  FaMedal,
  FaMicrophone,
  FaMoneyBillWave,
  FaMoon,
  FaMusic,
  FaPalette,
  FaRocket,
  FaSackDollar,
  FaScaleBalanced,
  FaSkull,
  FaStar,
  FaTag,
  FaTrophy,
  FaUser,
  FaWandMagicSparkles,
  FaWandSparkles,
} from "react-icons/fa6";
import { PiPianoKeysFill } from "react-icons/pi";

interface IconDef {
  Glyph: IconType;
  color: string;
}

export const ICONS = {
  home: { Glyph: FaHouse, color: "#7bd88f" },
  profile: { Glyph: FaIdCard, color: "#64b5f6" },
  trophy: { Glyph: FaTrophy, color: "#ffc93c" },
  target: { Glyph: FaBullseye, color: "#ff5c5c" },
  bag: { Glyph: FaBagShopping, color: "#c792ea" },
  handshake: { Glyph: FaHandshake, color: "#4dd0e1" },
  gear: { Glyph: FaGear, color: "#b0bec5" },

  coins: { Glyph: FaCoins, color: "#ffd54f" },
  user: { Glyph: FaUser, color: "#b0bec5" },
  lock: { Glyph: FaLock, color: "#8d99a6" },
  fire: { Glyph: FaFire, color: "#ff4d2e" },
  hourglass: { Glyph: FaHourglassHalf, color: "#4fc3f7" },
  award: { Glyph: FaAward, color: "#ffd54f" },

  gamepad: { Glyph: FaGamepad, color: "#8c7cff" },
  drum: { Glyph: FaDrum, color: "#ff7043" },
  palette: { Glyph: FaPalette, color: "#ec5f9e" },
  flawless: { Glyph: FaCheckDouble, color: "#5ed17a" },
  music: { Glyph: FaMusic, color: "#4db6ac" },
  medal: { Glyph: FaMedal, color: "#ffca28" },
  star: { Glyph: FaStar, color: "#ffd740" },
  crown: { Glyph: FaCrown, color: "#ffcf33" },
  bolt: { Glyph: FaBolt, color: "#ffe23d" },
  skull: { Glyph: FaSkull, color: "#e0e6ea" },
  link: { Glyph: FaLink, color: "#5c9dff" },
  rocket: { Glyph: FaRocket, color: "#ff6b3d" },
  globe: { Glyph: FaEarthAmericas, color: "#4fc3f7" },
  explosion: { Glyph: FaExplosion, color: "#ff5c5c" },
  moon: { Glyph: FaMoon, color: "#b39ddb" },
  versus: { Glyph: FaScaleBalanced, color: "#ef5350" },
  "money-bill": { Glyph: FaMoneyBillWave, color: "#5ed17a" },
  "sack-dollar": { Glyph: FaSackDollar, color: "#9ccc65" },
  "new-territory": { Glyph: FaCompass, color: "#26c6da" },
  "calendar-week": { Glyph: FaCalendarWeek, color: "#5c9dff" },
  calendar: { Glyph: FaCalendarDays, color: "#5c9dff" },

  sparkles: { Glyph: FaWandMagicSparkles, color: "#e26fff" },
  "face-smile": { Glyph: FaFaceSmile, color: "#ffca28" },
  border: { Glyph: FaBorderAll, color: "#b0bec5" },
  image: { Glyph: FaImage, color: "#4fc3f7" },
  tag: { Glyph: FaTag, color: "#ff8a65" },
  wand: { Glyph: FaWandSparkles, color: "#ce93d8" },
  gem: { Glyph: FaGem, color: "#4dd0e1" },

  guitar: { Glyph: FaGuitar, color: "#5ed17a" },
  microphone: { Glyph: FaMicrophone, color: "#ffca28" },
  piano: { Glyph: PiPianoKeysFill, color: "#e0e6ea" },
} satisfies Record<string, IconDef>;

export type IconName = keyof typeof ICONS;
