import type { IconType } from "react-icons";
import {
  FaAward,
  FaBagShopping,
  FaBolt,
  FaBorderAll,
  FaCalendarDays,
  FaCalendarWeek,
  FaCheckDouble,
  FaCoins,
  FaCompass,
  FaCrown,
  FaDrum,
  FaEarthAmericas,
  FaExplosion,
  FaFaceSmile,
  FaFire,
  FaGamepad,
  FaGear,
  FaGem,
  FaGuitar,
  FaHandshake,
  FaHourglassHalf,
  FaHouse,
  FaIdCard,
  FaImage,
  FaLink,
  FaLock,
  FaMedal,
  FaMicrophone,
  FaMoneyBillWave,
  FaMoon,
  FaMusic,
  FaPalette,
  FaRocket,
  FaSackDollar,
  FaScaleBalanced,
  FaSkull,
  FaStar,
  FaTag,
  FaTrophy,
  FaBullseye,
  FaUser,
  FaWandMagicSparkles,
  FaWandSparkles,
} from "react-icons/fa6";
import { PiPianoKeysFill } from "react-icons/pi";

export const ICONS = {
  home: FaHouse,
  profile: FaIdCard,
  trophy: FaTrophy,
  target: FaBullseye,
  bag: FaBagShopping,
  handshake: FaHandshake,
  gear: FaGear,

  coins: FaCoins,
  user: FaUser,
  lock: FaLock,
  fire: FaFire,
  hourglass: FaHourglassHalf,
  award: FaAward,

  gamepad: FaGamepad,
  drum: FaDrum,
  palette: FaPalette,
  flawless: FaCheckDouble,
  music: FaMusic,
  medal: FaMedal,
  star: FaStar,
  crown: FaCrown,
  bolt: FaBolt,
  skull: FaSkull,
  link: FaLink,
  rocket: FaRocket,
  globe: FaEarthAmericas,
  explosion: FaExplosion,
  moon: FaMoon,
  versus: FaScaleBalanced,
  "money-bill": FaMoneyBillWave,
  "sack-dollar": FaSackDollar,
  "new-territory": FaCompass,
  "calendar-week": FaCalendarWeek,
  calendar: FaCalendarDays,

  sparkles: FaWandMagicSparkles,
  "face-smile": FaFaceSmile,
  border: FaBorderAll,
  image: FaImage,
  tag: FaTag,
  wand: FaWandSparkles,
  gem: FaGem,

  guitar: FaGuitar,
  microphone: FaMicrophone,
  piano: PiPianoKeysFill,
} satisfies Record<string, IconType>;

export type IconName = keyof typeof ICONS;
